config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/blogs' => 'blogs#index'
  # post '/blogs' => 'blogs#create'
  root 'blogs#index'

  resources :blogs
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  
  def submitted
    self.created_at == self.updated_at ? 'Created' : 'Updated'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.all
  end

  #GET; form for new blog
  def new

  end

  def create
    @blog = Blog.new(blog_params)
    @blog.save

    redirect_to action: 'show', id: @blog.id
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def edit
    @blog = Blog.find(params[:id])
    # @errors = @blog.errors.full_message
  end

  def update
    # debugger
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to action: 'show', id: @blog.id
    else
      render 'edit'
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to root_path
  end

  private

    def blog_params
      params.require(:blog).permit(:body, :title)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogs/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form class="" action="/blogs/<%=@blog.id%>" method="post">
      <input type="hidden" name="_method" value="put">
      <input type="text" name="blog[title]" value="<%= @blog.title %>">
      <input type="submit" name="" value="Update">
      <textarea name="blog[body]" rows="10" cols="70"> <%=@blog.body%> </textarea>

      

  </form>
  </body>
</html>

app/views/blogs/index.html.erb
    <title>This is the blog index</title>

<body id='background'>

  <h3>All Blogs</h3>
<center>
  <div class="" style="">

    <% @blogs.each do |blog| %>
    <div class="main_blog">
      <p class="blog_title">
        <a href="/blogs/<%=blog.id%>"><%= blog.title %></a>
      </p>
      <p>
        <%= blog.body %>
      </p>

      <p class="time_submitted">
         <%=blog.submitted%> <%= time_ago_in_words(blog.created_at) %> ago.
      <p>
    </div>
    <% end %>

  </div>
</center>

</body>

app/views/blogs/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>new blog</title>
  </head>
  <body>
    <h4>New blog</h4>

    <%= form_for :blog, url: blogs_path do |f| %>
    <p>
      <%= f.label :title  %>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :body  %>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
    <% end %>

  </body>
</html>

app/views/blogs/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

  <div class="blog_full">

      <h4><%= @blog.title %></4>

      <p class="blog_body"> <%= @blog.body %> </li>

      <div class="time_submitted">
        <p class="home_links"> <%=@blog.submitted%> <%= time_ago_in_words(@blog.created_at)%> ago. </p>
        <p class="home_links"><a href="/blogs/<%=@blog.id%>/edit">Edit</a></p>
        <p class="home_links"> <%= link_to 'Destroy', [@blog],
        method: :delete,
        class: 'button',
        data: { confirm: 'Are you sure?' } %> </p>
      </div>


  </div>

  <br>
  <% if @errors %>
    <% @errors.each do |error| %>
    <ul>
      <li><%= error %> </li>
    </ul>
    <% end %>
  <% end %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <ul class='no_dot_list nav_bar'>
        <li class = 'home_links'><a href="/">Blogs</a></li>
        <li class = 'home_links'><a href="/blogs/new">New blog</a></li>
        <!-- <li class = 'home_links'><a href="#">log-in/log-out</a></li> -->

      </ul>
    </nav>

    <%= yield %>
  </body>
</html>